# Site settings
title:Jonny Peng Blog 
email:jonny.peng@qq.com
url: "http://jonnypeng.github.io/jonnypeng" # the base hostname & protocol for your site
twitter_username: jonnypeng
github_username:  Jonnypeng

# Build settings
markdown: kramdown



